# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0005_auto_20180514_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='users_liked',
            field=models.ManyToManyField(related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
