# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20180514_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
